[server]
headless = true
maxUploadSize = 1024
maxMessageSize = 1024
enableXsrfProtection = true
enableCORS = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1E4A68"
backgroundColor = "#F7F9FA"
secondaryBackgroundColor = "#EEF3F6"
textColor = "#1F2933"
font = "sans serif"
